---
apiVersion: 'external-secrets.io/v1beta1'
kind: ExternalSecret
metadata:
  name: {{ include ".fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "50"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  secretStoreRef:
    name: external-secrets-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ include ".fullname" . }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: /{{ .Values.env }}/{{ .Values.application | default ( include ".fullname" . ) }}/env
